# 表名称
tablename:
  BatchMaterial: "BulkImportDetail"                               # 批上传数据表
  BatchMaterialUniform: "batch_material_uniform"                  # 批数据向量表
  MainMaterial: "MATERIAL_ORIGINAL"                               # 主数据表
  MainMaterialUniform: "main_material_uniform"                    # 主数据向量表
  MaterialBatchResult: "MATERIAL_BATCH_RESULT"                    # 批量结果存储
  MaterialSingleResult: "MATERIAL_SINGLE_RESULT"                  # 单条结果存储
  StrReplaceInfo: "SpecialCharacters"                             # 字符替换表
# 基础变量
basevariable:
  similarthreshold: 0.98  # 默认相似度阈值
  startmp_threshold: 50   # 默认开启多进程计算向量的阈值
  core_process: 4         # 默认多进程核心数
  filterCondition: 0      # 筛选数据的条件
  expireTime: 6000        # redis中存储数据过期时间
# DB数据库
# '192.168.192.137'  测试环境
# '192.168.192.145'  生产环境
database:
  mssql:
#    url: "mssql+pymssql://sa:Bkdsj509@1.1.4.46:1433/yipin_zhj_x?charset=utf8"
    url: "mssql+pymssql://sa:root@1.1.4.66:1433/ZHJ_YIPIN?charset=utf8"
  busisness_mssql:
    url: "mssql+pymssql://sa:Bkdsj509@1.1.4.46:1433/zhjtest01?charset=utf8"
  mysql:
    url: "mysql+pymysql://root:123456@192.168.192.146:3306/db_onlymaterial_businessflow?charset=utf8"
  redis:
    config:
      host: "1.1.4.46"
      port: 6379
      db: 1    # 数据库号，默认0号
      pwd: 123456
  localcsv:
    url: ""
# 路径变量
path:
  log_path: 'H:\Project\pythonworkspace\ZHJ-YIPIN-X\ZHJYipinX\ZHJYipinX\logs\yipin.log'
